version: '3.8'

services:
  app:
    build:
      context: . # Dockerfile is in the current directory
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_HOST: ${DB_HOST}
      - DATABASE_PORT: ${DB_PORT}
      - DATABASE_NAME: ${DB_NAME}
      - DATABASE_USER: ${DB_USER}
      - DATABASE_PASSWORD: ${DB_PASSWORD}
    command: [ "poetry", "run", "python", "main.py" ]
    volumes:
      - .:/app # Optional: Mount the app directory for development

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB: ${DATABASE_NAME}
      - POSTGRES_USER: ${DATABASE_USER}
      - POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
